## Act 07 :

**Primero tenemos que ver la media de una muestra que tomamos de los alumnos para que sean hombres y con edad mayor igual a 21 y ver la media de altura**

In [ ]:
import csv
data = [
    ["H", 21, 1.73],
    ["M", 19, 1.62],
    ["H", 21, 1.73],
    ["H", 19, 1.69],
    ["H", 20, 1.75],
    ["H", 21, 1.80],
    ["H", 22, 1.70],
    ["H", 21, 1.75],
    ["H", 19, 1.66],
    ["M", 21, 1.64],
    ["M", 19, 1.62],
    ["H", 21, 1.85],
    ["H", 20, 1.75],
    ["H", 20, 1.66],
    ["H", 19, 1.70],
    ["H", 19, 1.64]
]
filename = 'datos_pizarron.csv'

with open(filename, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    # Escribir encabezados
    writer.writerow(["Genero", "Edad", "Altura"])
    # Escribir los datos
    writer.writerows(data)

In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("datos_pizarron.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Genero  16 non-null     object
 1   Edad    16 non-null     int64
 2   Altura  16 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 512.0+ bytes

In [15]:
df_fil = df[(df['Edad'] >= 21) & (df['Genero'] == 'H')]
df_fil

   Genero  Edad  Altura
0       H    21    1.73
2       H    21    1.73
5       H    21    1.80
6       H    22    1.70
7       H    21    1.75
11      H    21    1.85

In [ ]:
## promedio de altura 
df_fil['Altura'].mean()

np.float64(1.76)

## Actividad :

1. Tomar advertising.csv y hacer una regresion lineal simple

2. calcular   R2 de (1)

3. Usar 1 árbol de decision para regresion sobre el mismo dataset

4. Calcular R2 de (3)

5. Repetir ( paso 1-4 ) veces con train test split 50/50

* Usar la libreria de sklearn --> Decision Tree Regressor

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

df = pd.read_csv('../Data/Advertising.csv')
df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [25]:
df = df.drop(columns=[col for col in df.columns if 'Unnamed' in col], errors='ignore')

### Sacamos variales para nuestros modelitos

In [28]:
X = df[['TV', 'radio', 'newspaper']]
y = df['sales']

In [29]:
# Regresión Lineal
lr = LinearRegression()
lr.fit(X, y)
y_pred_lr_all = lr.predict(X)
r2_lr_all = r2_score(y, y_pred_lr_all)

In [30]:
# Árbol de Decisión
tree = DecisionTreeRegressor(random_state=42)
tree.fit(X, y)
y_pred_tree_all = tree.predict(X)
r2_tree_all = r2_score(y, y_pred_tree_all)

#### Con train y test :

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=42
)

#RL
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
r2_lr = r2_score(y_test, y_pred_lr)

#Árbol
tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)
r2_tree = r2_score(y_test, y_pred_tree)

In [34]:
print("USANDO TODO EL DATASET ")
print("R2 Regresión Lineal:", r2_lr_all)
print("R2 Árbol de Decisión:", r2_tree_all)

USANDO TODO EL DATASET
R2 Regresión Lineal: 0.8972106381789522
R2 Árbol de Decisión: 1.0

In [35]:
print(" TRAIN / TEST 50/50 ")
print("R2 Regresión Lineal:", r2_lr)
print("R2 Árbol de Decisión:", r2_tree)

 TRAIN / TEST 50/50
R2 Regresión Lineal: 0.8721004816045136
R2 Árbol de Decisión: 0.9344975035059896

Con árbol salió mejor R2 en comparación al RL en los dos